import { z } from 'zod';

export enum PlatformEventType {
  HOSPITAL_APPROVED = 'HOSPITAL_APPROVED',
  DOCTOR_CREATED = 'DOCTOR_CREATED',
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  QUESTIONNAIRE_ASSIGNED = 'QUESTIONNAIRE_ASSIGNED',
  QUESTIONNAIRE_COMPLETED = 'QUESTIONNAIRE_COMPLETED',
  AI_CONVERSATION_STARTED = 'AI_CONVERSATION_STARTED',
  CAPABILITY_EXECUTED = 'CAPABILITY_EXECUTED',
  EHR_OPERATION_STARTED = 'EHR_OPERATION_STARTED',
  EHR_OPERATION_COMPLETED = 'EHR_OPERATION_COMPLETED',
  EHR_OPERATION_FAILED = 'EHR_OPERATION_FAILED',
  EXTERNAL_VERIFICATION_COMPLETED = 'EXTERNAL_VERIFICATION_COMPLETED',
  RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED',
  WORKFLOW_STARTED = 'WORKFLOW_STARTED',
  WORKFLOW_COMPLETED = 'WORKFLOW_COMPLETED',
  WORKFLOW_FAILED = 'WORKFLOW_FAILED',
  HUMAN_ESCALATION = 'HUMAN_ESCALATION',
}

export interface PlatformEvent<T = any> {
  id: string;
  type: PlatformEventType;
  correlationId: string;
  tenantId?: string;
  timestamp: string;
  payload: T;
}
